### ISSUE TITLE
Cannot create content with Binary attachment

### ISSUE THREAD

**Issue by ByteCode2408** [SenseNet/sn-client-core#35]
Hi,
Maybe it's not the right place to ask, but I have defined in sensenet a content type which extends File, and has some additional text fields. Using sn-client-core from Aurelia typescript I'm able to create the content without the Binary attachment, but the problem is when I want to populate the Binary field from an input file, by taking for example evt.target.files[0], the uploaded file has 0bytes. If you please provide me an example of how cand I achieve this.

Many many thanks!

**Comment by gallayl** [comment]
Hi,

A simple ```repository.post()``` won't upload binaries, sensenet (and therefore the core client package) has a different [API endpoint](https://community.sensenet.com/api/@sensenet/client-core/classes/upload.html) for that - and also supports [chunked uploads](http://wiki.sensenet.com/Upload_action), multiple uploads, etc....

You can check out [this](https://github.com/gallayl/sn-explore-aurelia/blob/master/src/explore/explore.ts#L177) Aurelia example (it uploads file(s) or a folder structure from a drop event) or if you want to use a fileList (files / folders from a file input) you can use the [``Upload.fromFileList()``](https://github.com/SenseNet/sn-client-core/blob/master/src/Repository/Upload.ts#L292) endpoint.

If you still have problems you can post an example code or a link to an example project.

**Comment by kultsar** [comment]
@ByteCode2408, closing this for now, but feel free to reopen this or open another issue.
